version: '3'
services:
  redis:
    image: "redislabs/redisearch:latest"
    container_name: redis
    ports:
      - "6379:6379"
  jupyter:
    image: jupyter/minimal-notebook
    volumes:
      - ../src/:/home/jovyan/scripts
    ports:
      - 8888:8888
    container_name: jupyter
    depends_on:
      - redis

  insight:
    image: "redislabs/redisinsight:latest"
    container_name: insight
    ports:
      - "8001:8001"
    volumes:
      - ../redisinsight:/db
    depends_on:
      - redis

